import type {AnyFileStatement} from 'onecfg';
import {defineTextFile, mergeContent} from 'onecfg';
import {git} from './git.js';
import {prettier} from './prettier.js';
import {vscode} from './vscode.js';

const configFile = defineTextFile(`.npmrc`, [
  `# Automatically generated by onecmd, please do not change directly.`,
]);

/** https://www.npmjs.com */
export const npm = (): readonly AnyFileStatement[] => [
  configFile,

  mergeContent(git.ignoreFile, [`node_modules`]),
  mergeContent(prettier.ignoreFile, [`package-lock.json`]),

  mergeContent(vscode.extensionsFile, {
    recommendations: [`eg2.vscode-npm-script`],
  }),

  mergeContent(vscode.settingsFile, {
    'files.exclude': {
      [configFile.path]: true,
      'node_modules': true,
      'package-lock.json': true,
    },
  }),
];

npm.configFile = configFile;
